import { MenuItem } from './types';

export const MENU_DATA: MenuItem[] = [
  // Entrantes
  {
    id: '1',
    name: 'Gamba Roja de Dénia (Extra)',
    description: 'Joyas del Mediterráneo cocidas en agua de mar o a la plancha con sal gorda.',
    price: 45,
    category: 'Mariscos Frescos',
    allergens: ['Crustáceos'],
    image: 'https://laxernadelmar.com/wp-content/uploads/2018/08/gamba.jpg',
    featured: true
  },
  {
    id: '2',
    name: 'Ostras Speciale de Claire nº2',
    description: 'Unidad de ostra francesa de sabor equilibrado y textura firme.',
    price: 6.5,
    category: 'Mariscos Frescos',
    allergens: ['Moluscos'],
    image: 'https://static.wixstatic.com/media/28b472_3a7e70cc6cd3489ba557926666ec5552~mv2.jpg/v1/fill/w_480,h_320,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/28b472_3a7e70cc6cd3489ba557926666ec5552~mv2.jpg',
  },
  {
    id: '3',
    name: 'Carpaccio de Gamba Blanca',
    description: 'Finas láminas de gamba de la bahía con aceite de oliva virgen extra y toque de lima.',
    price: 24,
    category: 'Entrantes',
    allergens: ['Crustáceos'],
    image: 'https://img2.rtve.es/n/16065816?w=1600',
  },
  {
    id: '4',
    name: 'Navajas de Buceo a la Plancha',
    description: 'Con un majado de ajo, perejil y un toque de vino blanco Albariño.',
    price: 18,
    category: 'Entrantes',
    allergens: ['Moluscos'],
    image: 'https://i.blogs.es/58a40a/navajas_aumen/840_560.jpg',
  },
  {
    id: '5',
    name: 'Arroz con Bogavante (Mín. 2 pers)',
    description: 'Arroz meloso elaborado con bogavante azul nacional y fumet de roca.',
    price: 32, // por persona
    category: 'Arroces',
    allergens: ['Crustáceos', 'Pescado', 'Moluscos'],
    image: 'https://canalcocina.es/medias/_cache/zoom-fda9f4e32f5d1ad4f42ec9bd3597cb2e-920-518.jpg',
    featured: true
  },
  {
    id: '6',
    name: 'Rodaballo Salvaje a la Gallega',
    description: 'Pieza capturada en libertad, servida con ajada tradicional y patata cocida.',
    price: 38,
    category: 'Pescados',
    allergens: ['Pescado'],
    image: 'https://www.plenussupermercados.es/wp-content/uploads/2024/04/rodaballo-a-la-gallega.jpg',
  },
  {
    id: '7',
    name: 'Cigalas Reales al Horno',
    description: 'Cigalas de gran calibre con una suave costra de pan de especias y hierbas.',
    price: 52,
    category: 'Mariscos Frescos',
    allergens: ['Crustáceos', 'Gluten'],
    image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiybNp9aswHxmqmwaKcitkxRu9oPXr6hNH7wm4vddHv1kJ7_FrNLmHEQQxjUxXRY2fMaAW357hQ8i_Y1ZawQB6USN9T2MYfaUdQchygeUzXlQzEN60-q-OrK7nFqkSbwhxgJ6ydCHOYl5s/w1200-h630-p-k-no-nu/Cigalas+al+horno-12.jpg',
  },
  {
    id: '8',
    name: 'Fideuá de Gandía',
    description: 'Fideo fino con gamba roja y cigalas, servida con alioli de azafrán.',
    price: 26,
    category: 'Arroces',
    allergens: ['Gluten', 'Crustáceos', 'Pescado', 'Huevos'],
    image: 'https://www.pastaslacatalana.com/wp-content/uploads/2017/09/fideua-de-gandia.jpg',
  },
  {
    id: '9',
    name: 'Salpicón de Marisco Royal',
    description: 'Langosta, buey de mar y gambas con vinagreta de pimientos y cebolleta morada.',
    price: 28,
    category: 'Entrantes',
    allergens: ['Crustáceos', 'Moluscos'],
    image: 'https://canalcocina.es/medias/_cache/zoom-9ff14f585af4f7f45d0ebef86034c628-920-518.jpg',
  },
  {
    id: '10',
    name: 'Lubina a la Sal de las Salinas de Santa Pola',
    description: 'Lubina de estero preparada a la sal para mantener toda su jugosidad (aprox 1kg).',
    price: 48,
    category: 'Pescados',
    allergens: ['Pescado'],
    image: 'https://i.blogs.es/6c0ecd/lubina_sal-copia/832_435.jpg',
  },
  {
    id: '11',
    name: 'Almejas de Carril a la Marinera',
    description: 'Salsa tradicional con vino fino, cebolla pochada y una pizca de pimentón de la Vera.',
    price: 22,
    category: 'Entrantes',
    allergens: ['Moluscos', 'Gluten', 'Dióxido de azufre'],
    image: 'https://canalcocina.es/medias/_cache/zoom-5974cbb7dcfad79e2d87904f0d05471a-920-518.jpg',
  },
  {
    id: '12',
    name: 'Tartar de Atún Rojo Balfegó',
    description: 'Con aguacate, algas wakame y un toque sutil de soja y jengibre.',
    price: 26,
    category: 'Entrantes',
    allergens: ['Pescado', 'Soja', 'Sésamo'],
    image: 'https://images.unsplash.com/photo-1501595091296-3a9f4fe6825c?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '13',
    name: 'Arroz Negro con Sepia y Gambas',
    description: 'Arroz seco en paella con tinta de calamar y tropezones de costa.',
    price: 24,
    category: 'Arroces',
    allergens: ['Moluscos', 'Crustáceos', 'Pescado'],
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '14',
    name: 'Sorpresa de Chocolate Negro 70%',
    description: 'Coulant con corazón líquido y helado de vainilla de Madagascar.',
    price: 9,
    category: 'Postres',
    allergens: ['Lácteos', 'Huevos', 'Gluten'],
    image: 'https://images.unsplash.com/photo-1563805042-7684c849a135?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '15',
    name: 'Tarta de Queso de Autor',
    description: 'Extremadamente cremosa, con base de galleta artesana y frutos rojos.',
    price: 8.5,
    category: 'Postres',
    allergens: ['Lácteos', 'Huevos', 'Gluten'],
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '16',
    name: 'Albariño Pazo de Señorans',
    description: 'D.O. Rías Baixas. Elegante, con notas críticas y final salino.',
    price: 35,
    category: 'Vinos',
    allergens: ['Dióxido de azufre'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '17',
    name: 'Champagne Laurent-Perrier La Cuvée',
    description: 'De gran finura y una bella frescura obtenida tras una larga crianza.',
    price: 75,
    category: 'Vinos',
    allergens: ['Dióxido de azufre'],
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '18',
    name: 'Percebes de la Costa da Morte',
    description: 'Hervidos en su punto justo de sal con laurel.',
    price: 60,
    category: 'Mariscos Frescos',
    allergens: ['Crustáceos'],
    image: 'https://images.unsplash.com/photo-1626202133282-36e2f1db8e70?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '19',
    name: 'Carpaccio de Pulpo con Aceite de Pimentón',
    description: 'Finas láminas de pulpo gallego con escamas de sal y AOVE.',
    price: 20,
    category: 'Entrantes',
    allergens: ['Moluscos'],
    image: 'https://gourmet.expob2b.es/uploads/fotos_noticias/2018/01/w800px_16824-132866-ensalada-de-carpaccio-de-pulpo-con-aceite-de-pimenton.jpg',
  },
  {
    id: '20',
    name: 'Milhojas de Crema y Nata',
    description: 'Hojaldre invertido crujiente con crema pastelera a la vainilla.',
    price: 9,
    category: 'Postres',
    allergens: ['Gluten', 'Lácteos', 'Huevos'],
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '21',
    name: 'Marqués de Riscal Reserva',
    description: 'D.O. Ca. Rioja. Un clásico con aromas de fruta madura y toques complejos de crianza.',
    price: 28,
    category: 'Vinos',
    allergens: ['Dióxido de azufre'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '22',
    name: 'Muga Prado Enea Gran Reserva',
    description: 'D.O. Ca. Rioja. Vino de gran elegancia, con notas de cuero y especias dulces.',
    price: 65,
    category: 'Vinos',
    allergens: ['Dióxido de azufre'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '23',
    name: 'José Pariente Verdejo',
    description: 'D.O. Rueda. Fresco, afrutado y con el característico toque amargo del verdejo.',
    price: 22,
    category: 'Vinos',
    allergens: ['Dióxido de azufre'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '24',
    name: 'Gramona Imperial Brut Nature',
    description: 'CORPINNAT. Espumoso de larga crianza, elegante y muy gastronómico.',
    price: 36,
    category: 'Vinos',
    allergens: ['Dióxido de azufre'],
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '25',
    name: 'Pulpo a la Brasa con Parmentier',
    description: 'Pulpo tierno sobre crema suave de patata y aceite de pimentón de la Vera.',
    price: 24,
    category: 'Entrantes',
    allergens: ['Moluscos', 'Lácteos'],
    image: 'https://images.unsplash.com/photo-1559132109-17bf48696ab7?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '26',
    name: 'Escalivada con Anchoas del Cantábrico',
    description: 'Verduras asadas a la leña combinadas con anchoas de primera calidad.',
    price: 16,
    category: 'Entrantes',
    allergens: ['Pescado'],
    image: 'https://www.conservasnardin.com/img/cms/escalivada-anchoas-2.jpg',
  },
  {
    id: '27',
    name: 'Calamar de Potera a la Plancha',
    description: 'Producto fresco de temporada, con una picada de ajo y perejil.',
    price: 22,
    category: 'Pescados',
    allergens: ['Moluscos'],
    image: 'https://live.staticflickr.com/3925/14773301108_666733aff5_b.jpg',
  },
  {
    id: '28',
    name: 'Paella Valenciana Tradicional',
    description: 'Con pollo, conejo y verdura de temporada. Receta clásica levantina.',
    price: 19,
    category: 'Arroces',
    allergens: [],
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '29',
    name: 'Lenguado Erizado con Alcaparras',
    description: 'Filetes de lenguado con mantequilla negra y alcaparras fritas.',
    price: 28,
    category: 'Pescados',
    allergens: ['Pescado', 'Lácteos'],
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '30',
    name: 'Bogavante Nacional Termidor',
    description: 'Preparación clásica con salsa termidor y gratinado al horno.',
    price: 55,
    category: 'Mariscos Frescos',
    allergens: ['Crustáceos', 'Lácteos', 'Mostaza'],
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80&w=800',
  }
];
